name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Extract Version
        id: get_version
        uses: battila7/get-version-action@v2.3.0

      - name: Modify manifest file
        id: sub_manifest_link_version
        uses: cschleiden/replace-tokens@v1.3
        with:
          files: '["system.json", "packs/src/**/*.json"]'
        env:
          VERSION: ${{ steps.get_version.outputs.version-without-v }}

      - name: Build
        run: npm install && npm run build

      - name: Get Changelog
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.get_version.outputs.version-without-v }}
          path: ./CHANGELOG.md

      - name: Create archive
        run: |
          zip                                    \
            --recurse-paths                      \
            ./taluspnp.zip                       \
            assets/                              \
            css/                                 \
            lang/                                \
            module/                              \
            packs/                               \
            templates/                           \
            CHANGELOG.md                         \
            LICENSE.txt                          \
            README.md                            \
            system.json                          \
            template.json                        \
            --exclude                            \
            "packs/src/*"                       

      # Update the GitHub release with the manifest and system archive files.
      - name: Update Release With Files
        id: create_version_release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./taluspnp.zip'
          name: ${{ steps.get_version.outputs.version-without-v }}
          tag: ${{ steps.get_version.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}

      - name: Release
        uses: illandril/FoundryVTT-package-release-action@v1.0.1
        with:
          package-release-token: ${{ secrets.PACKAGE_RELEASE_TOKEN }}
          manifest-url: "https://github.com/${{ github.repository }}/releases/download/${{ steps.get_version.outputs.version-without-v }}/system.json"
